import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/query-provider";
import ParticlesBackground from "@/components/ParticlesBackground";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head />
            <body className="relative min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
                <QueryProvider>
                    {/* Particle Background */}
                    <ParticlesBackground />
                    {/* Navbar */}
                    <Navbar />
                    {/* Foreground content */}
                    <div className="relative z-10">
                        {children}
                        <Toaster />
                    </div>
                </QueryProvider>
            </body>
        </html>
    );
}
