import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/query-provider";
import ParticlesBackground from "@/components/ParticlesBackground";

export const metadata: Metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head />
            <body className="relative min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 overflow-hidden">
                {/* Particle Background */}
                <ParticlesBackground />

                {/* Foreground content */}
                <div className="relative z-10">
                    <QueryProvider>
                        {children}
                        <Toaster />
                    </QueryProvider>
                </div>
            </body>
        </html>
    );
}
